import { StockItem, Warehouse, StockMovement, SAFTInvoiceSim, UserRole } from "./types";

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: "WH-CENTRAL",
    name: "Loja Central (Luanda)",
    location: "Via S8, Talatona, Edifício AMADJE, Luanda",
    manager: "Eng. António Bastos",
    contact: "+244 923 456 789",
  },
  {
    id: "WH-LUANDA",
    name: "Loja Luanda (Maianga)",
    location: "Rua Amílcar Cabral, Maianga, Luanda",
    manager: "Dra. Maria Kiluanje",
    contact: "+244 912 888 111",
  },
  {
    id: "WH-BENGUELA",
    name: "Loja Benguela",
    location: "Zona Industrial de Benguela, Galpão B",
    manager: "Sr. Carlos Fonseca",
    contact: "+244 934 555 222",
  },
  {
    id: "WH-LOBITO",
    name: "Loja Lobito",
    location: "Largo do Lobito, Benguela/Lobito",
    manager: "Sr. João Gime",
    contact: "+244 945 999 333",
  },
];

export const INITIAL_ITEMS: StockItem[] = [
  // Pharmaceutical products from the mockup image
  {
    id: "item-1",
    name: "Paracetamol 500mg",
    sku: "PRD-00045",
    barcode: "5601234567890",
    category: "Farmacêuticos",
    currentStock: 350,
    minStock: 100,
    maxStock: 800,
    unit: "UN",
    price: 1500, // 1,500 Kwanza (AOA)
    location: "Corredor A - Prateleira 2",
    warehouse: "Loja Central (Luanda)",
    lot: "L240515",
    expiryDate: "2026-05-15",
    status: "normal",
  },
  {
    id: "item-2",
    name: "Amoxicilina 500mg",
    sku: "PRD-00122",
    barcode: "5609876543210",
    category: "Farmacêuticos",
    currentStock: 80,
    minStock: 150, // CRITICAL: Below minimum stock
    maxStock: 600,
    unit: "UN",
    price: 3200,
    location: "Corredor A - Prateleira 4",
    warehouse: "Loja Luanda (Maianga)",
    lot: "L240630",
    expiryDate: "2026-09-30",
    status: "critico",
  },
  {
    id: "item-3",
    name: "Ibuprofeno 400mg",
    sku: "PRD-00099",
    barcode: "5601112223334",
    category: "Farmacêuticos",
    currentStock: 430,
    minStock: 100,
    maxStock: 1000,
    unit: "UN",
    price: 1800,
    location: "Corredor B - Prateleira 1",
    warehouse: "Loja Benguela",
    lot: "L240410",
    expiryDate: "2026-04-10", // Near expiry or expired based on 2026 current time
    status: "normal",
  },
  {
    id: "item-4",
    name: "Omeprazol 20mg",
    sku: "PRD-00350",
    barcode: "5604445556667",
    category: "Farmacêuticos",
    currentStock: 220,
    minStock: 50,
    maxStock: 500,
    unit: "UN",
    price: 2100,
    location: "Corredor B - Prateleira 3",
    warehouse: "Loja Central (Luanda)",
    lot: "L240901",
    expiryDate: "2026-12-01",
    status: "normal",
  },
  // VBSP Technical Services & Installation equipment
  {
    id: "item-5",
    name: "Câmara Bullet IP VBSP Ultra-HD 4K",
    sku: "SEC-CCTV4K",
    barcode: "7891234500012",
    category: "Sistemas de Segurança",
    currentStock: 12,
    minStock: 15, // CRITICAL: Below minimum
    maxStock: 100,
    unit: "UN",
    price: 85000,
    location: "Armário Técnico 1",
    warehouse: "Loja Central (Luanda)",
    lot: "L-CCTV-2026",
    status: "critico",
  },
  {
    id: "item-6",
    name: "Cabo de Rede Nexans Cat6 UTP (Bobina 305m)",
    sku: "CAB-CAT6UTP",
    barcode: "7891234500029",
    category: "Cablagem e Conectores",
    currentStock: 45,
    minStock: 10,
    maxStock: 150,
    unit: "BOBINA",
    price: 125000,
    location: "Corredor C - Palete 4",
    warehouse: "Loja Luanda (Maianga)",
    lot: "L-CAB-26",
    status: "normal",
  },
  {
    id: "item-7",
    name: "Router de Fibra Óptica GPON VBSP Wi-Fi 6",
    sku: "NET-GPONWF6",
    barcode: "7891234500036",
    category: "Redes e Telecomunicações",
    currentStock: 0,
    minStock: 20, // OUT OF STOCK
    maxStock: 120,
    unit: "UN",
    price: 68000,
    location: "Prateleira Eletrónicos B",
    warehouse: "Loja Central (Luanda)",
    lot: "L-RT-0126",
    status: "sem-stock",
  },
  {
    id: "item-8",
    name: "Central de Incêndio Endereçável VBSP-FireX",
    sku: "DET-FIREX100",
    barcode: "7891234500043",
    category: "Deteção de Incêndio",
    currentStock: 5,
    minStock: 3,
    maxStock: 20,
    unit: "UN",
    price: 495000,
    location: "Zona de Carga Especial",
    warehouse: "Loja Lobito",
    lot: "L-FIRE-2026",
    status: "normal",
  },
];

export const INITIAL_MOVEMENTS: StockMovement[] = [
  {
    id: "MOV-0001",
    type: "entrada",
    itemId: "item-1",
    itemName: "Paracetamol 500mg",
    sku: "PRD-00045",
    toWarehouse: "Loja Central (Luanda)",
    quantity: 120,
    date: "2026-07-04 09:15",
    user: "António Bastos",
    reference: "GR-VBSP-2026-0043",
    lot: "L240515",
    notes: "Receção de fornecedor local com guia de remessa",
  },
  {
    id: "MOV-0002",
    type: "saida",
    itemId: "item-2",
    itemName: "Amoxicilina 500mg",
    sku: "PRD-00122",
    fromWarehouse: "Loja Luanda (Maianga)",
    quantity: 80,
    date: "2026-07-04 14:30",
    user: "Maria Kiluanje",
    reference: "FT-2026/04321", // SAFT Fatura
    lot: "L240630",
    notes: "Faturação direta AGT para Clínica do Kilamba",
  },
  {
    id: "MOV-0003",
    type: "transferencia",
    itemId: "item-3",
    itemName: "Ibuprofeno 400mg",
    sku: "PRD-00099",
    fromWarehouse: "Loja Central (Luanda)",
    toWarehouse: "Loja Benguela",
    quantity: 60,
    date: "2026-07-05 10:00",
    user: "Sistemas VBSP",
    reference: "GT-VBSP-2026-0012",
    lot: "L240410",
    notes: "Transferência interna de stock excedente",
  },
  {
    id: "MOV-0004",
    type: "entrada",
    itemId: "item-4",
    itemName: "Omeprazol 20mg",
    sku: "PRD-00350",
    toWarehouse: "Loja Central (Luanda)",
    quantity: 200,
    date: "2026-07-05 11:24",
    user: "António Bastos",
    reference: "GR-VBSP-2026-0044",
    lot: "L240901",
    notes: "Entrada de stock urgente importado",
  },
  {
    id: "MOV-0005",
    type: "entrada",
    itemId: "item-6",
    itemName: "Cabo de Rede Nexans Cat6 UTP (Bobina 305m)",
    sku: "CAB-CAT6UTP",
    toWarehouse: "Loja Luanda (Maianga)",
    quantity: 15,
    date: "2026-07-05 12:10",
    user: "Maria Kiluanje",
    reference: "GR-VBSP-2026-0045",
    lot: "L-CAB-26",
    notes: "Reposição de stock para projetos de IT",
  },
];

export const INITIAL_INVOICES: SAFTInvoiceSim[] = [
  {
    id: "INV-001",
    invoiceNo: "FT VBSP2026/00001",
    customerName: "Hospital Geral de Luanda",
    customerNif: "540112345",
    date: "2026-07-01",
    amount: 250000,
    taxAmount: 35000, // 14% IVA Angola
    itemsCount: 3,
    status: "emitida",
  },
  {
    id: "INV-002",
    invoiceNo: "FT VBSP2026/00002",
    customerName: "Telecomunicações de Angola, SA",
    customerNif: "541987654",
    date: "2026-07-03",
    amount: 1450000,
    taxAmount: 203000,
    itemsCount: 5,
    status: "emitida",
  },
  {
    id: "INV-003",
    invoiceNo: "FT VBSP2026/00003",
    customerName: "Clínica Sagrada Esperança",
    customerNif: "540222111",
    date: "2026-07-04",
    amount: 120000,
    taxAmount: 16800,
    itemsCount: 1,
    status: "emitida",
  },
];

export const SYSTEM_USERS: UserRole[] = [
  {
    username: "admin",
    name: "Administrador Geral (AMADJE)",
    role: "admin",
    email: "admin@amadje.ao",
    avatar: "AG"
  },
  {
    username: "operador-luanda",
    name: "Maria Kiluanje (Maianga)",
    role: "operador",
    assignedStore: "Loja Luanda (Maianga)",
    email: "luanda@amadje.ao",
    avatar: "MK"
  },
  {
    username: "operador-benguela",
    name: "Carlos Fonseca (Benguela)",
    role: "operador",
    assignedStore: "Loja Benguela",
    email: "benguela@amadje.ao",
    avatar: "CF"
  },
  {
    username: "operador-lobito",
    name: "João Gime (Lobito)",
    role: "operador",
    assignedStore: "Loja Lobito",
    email: "lobito@amadje.ao",
    avatar: "JG"
  }
];

